GLOSSARY: dict[str, str] = {
    "CASA": "current account savings account",
    "CAR": "capital adequacy ratio",
    "CIR": "cost-to-income ratio",
    "NII": "net interest income",
    "NFI": "net fee and commission income",
    "NIM": "net interest margin",
    "NPL": "non-performing loan",
    "PBT": "profit before tax",
    "TOI": "total operating income",
    "ROA": "return on assets",
    "ROE": "return on equity",
    "LDR": "loan-to-deposit ratio",
    "LC": "letters of credit",
    "FX": "foreign exchange",
    "IB": "investment banking",
    "IPO": "initial public offering",
    "SBV": "State Bank of Vietnam",
    "TCBS": "Techcom Securities",
    "TCGI": "Techcom General Insurance",
    "YoY": "year-on-year",
    "YTD": "year-to-date",
    "QoQ": "quarter-on-quarter",
    "LTM": "last twelve months",
    "HOSE": "Ho Chi Minh Stock Exchange",
    "HNX": "Hanoi Stock Exchange",
    "UPAS LC": "usance payable at sight letter of credit",
}
